### PR TITLE
Chore: Update MetaData for IVORY COAST

### PR DESCRIPTION
**Pull request by hkairi**

### CODE REVIEW

**Comment by joshwetzel** [comment]
Hello! Thanks for submitting this pull request.

Did you pull these changes directly from our upstream (https://github.com/google/libphonenumber)? If so, were other changes excluded?

**Comment by hkairi** [comment]
Hello

Did you pull these changes directly from our upstream (https://github.com/google/libphonenumber) -- Yes 

I only took changes for IVORY COAST ( country_code="CI" )

**Comment by joshwetzel** [comment]
Is `data/telephone_number_data_file.dat` correct? I'm seeing a diff when I generate it using your XML.

**Comment by hkairi** [comment]
`data/telephone_number_data_file.dat` is correct. I am using it in my application right now and the validation is working as expected.

**Comment by joshwetzel** [comment]
Thanks for your patience. We will include these changes as part of a larger metadata update rather than cutting a new release specifically for this. It is something I plan on working on next week.

**Comment by joshwetzel** [comment]
These updates were included with https://github.com/mobi/telephone_number/pull/95. Thanks again for your patience.

**Pull request closed without merging**
